-- add indexing

CREATE TABLE user (
    id INT PRIMARY KEY NOT NULL,
    username VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    language DEFAULT 'en',
    settings JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE virtual_room (
    id INT PRIMARY KEY NOT NULL,
    user_id INT NOT NULL FOREIGN KEY REFERENCES user(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    is_active BOOLEAN,
    active_user_count INT DEFAULT 0,
    room_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE user_virtual_room_session (
    id INT PRIMARY KEY NOT NULL,
    user_id INT NOT NULL FOREIGN KEY REFERENCES user(id) ON DELETE CASCADE,
    room_id INT NOT NULL FOREIGN KEY REFERENCES virtual_room(id) ON DELETE CASCADE,
    position JSON,
    status ENUM('idle', 'offline', 'online'),
    mic_enabled BOOLEAN,
    video_enabled BOOLEAN,
    screen_sharing BOOLEAN,
    joined_at TIMESTAMP,
    last_seen TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE chat (
    id INT PRIMARY KEY,
    room_id INT NOT NULL FOREIGN KEY REFERENCES virtual_room(id) ON DELETE CASCADE,
    user_id INT NOT NULL FOREIGN KEY REFERENCES user(id) ON DELETE CASCADE,
    message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
);

CREATE TABLE video_call (
    id INT PRIMARY KEY,
    room_id INT NOT NULL FOREIGN KEY REFERENCES virtual_room(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);